const Catagories = [
  {
    name: "Silk-Saree",
    description: "Description of Product 1",
    price: " 199",
    image: "photo/women-3.jpg",
    category: "Cloths",
  },
  {
    name: "Casual Shirt",
    description: "Description of Product 3",
    price: " 399",
    image: "photo/men-1.jpg",
    category: "Cloths",
  },
  {
    name: "Titan Watch",
    description: "Description of Product 4",
    price: " 499",
    image: "photo/watch-2.jpg",
    category: "Watches",
  },
  {
    name: "Airdopes",
    description: "Description of Product 4",
    price: " 299",
    image: "photo/image1.png",
    category: "Headphone",
  },
  {
    name: "Storm",
    description: "Description of Product 4",
    price: " 299",
    image: "photo/image6.png",
    category: "Watches",
  },
  {
    name: "Neckband",
    description: "Description of Product 4",
    price: " 299",
    image: "photo/image9.png",
    category: "Headphone",
  },
  {
    name: "western",
    description: "Description of Product 1",
    price: " 199",
    image: "photo/women-2.jpg",
    category: "Cloths",
  },
  {
    name: "Rockerz",
    description: "Description of Product 3",
    price: " 399",
    image: "photo/image16.png",
    category: "Headphone",
  },
  {
    name: "Salwar Suit",
    description: "Description of Product 1",
    price: " 199",
    image: "photo/women-4.jpg",
    category: "Cloths",
  },
  {
    name: "wave call",
    description: "Description of Product 3",
    price: " 399",
    image: "photo/watch-3.jpg",
    category: "Watches",
  },
  {
    name: "Rockid Rush",
    description: "Description of Product 4",
    price: " 499",
    image: "photo/image13.png",
    category: "Headphone",
  },
  {
    name: "Chex-Shirts",
    description: "Description of Product 4",
    price: " 299",
    image: "photo/men-2.jpg",
    category: "Cloths",
  },
];
export default Catagories;
