const Catagories = [
  {
    productId: "1",
    name: "Silk-Saree",
    description:
      "SGF11 Women's Trendy Kanjivaram Soft Lichi Silk Saree With Blouse Piece SWADESI STUFF Georgette Saree with Banglory Silk Blouse & Stunning Crystal Fix Embellishments - Indian Ethnic Wear for Women",
    price: " 199",
    image: "/photo/women1.jpeg",
    category: "Cloths",
    im1: "/photo/women-3.jpg",
    im2: "/photo/women5.jpeg",
    im3: "/photo/women8.jpeg",
  },
  {
    productId: "2",
    name: "Casual Shirt",
    description:
      "GRECIILOOKS Men Solid Regular Fit Casual Shirt Lymio Casual Shirt for Men|| Shirt for Men|| Men Stylish Shirt",
    price: " 399",
    image: "/photo/men-1.jpg",
    category: "Cloths",
    im1: "/photo/men3.jpg",
    im2: "/photo/men4.png",
    im3: "/photo/men-2.jpg",
  },
  {
    productId: "3",
    name: "Titan Watch",
    description:
      "Noise Twist Go Round dial Smartwatch with BT Calling, 1.39 Display, Metal Build, 100+ Watch Faces, IP68, Sleep Tracking, 100+ Sports Modes, 24/7 Heart Rate Monitoring (Jet Black)",
    price: " 499",
    image: "/photo/watch-2.jpg",
    category: "Watches",
    im1: "/photo/watch-3.jpg",
    im2: "/photo/image5.png",
    im3: "/photo/image8.png",
  },
  {
    productId: "4",
    name: "Airdopes",
    description:
      "Fastrack Fpods(New Launch) FX100 Bluetooth TWS In-Ear Earbuds with 40 Hrs Playtime|BT V5.3|13mm Extra Deep Bass Drivers|Quad Mic ENC for Clear Calls|Ultra Low 50ms Latency Gaming Mode|NitroFast Charge",
    price: " 299",
    image: "/photo/image1.png",
    category: "Headphone",
    im1: "/photo/image3.png",
    im2: "/photo/image4.png",
    im3: "/photo/image2.png",
  },
  {
    productId: "5",
    name: "Storm",
    description:
      "Noise Twist Go Round dial Smartwatch with BT Calling, 1.39 Display, Metal Build, 100+ Watch Faces, IP68, Sleep Tracking, 100+ Sports Modes, 24/7 Heart Rate Monitoring (Jet Black)",
    price: " 299",
    image: "/photo/image6.png",
    category: "Watches",
    im1: "/photo/image7.png",
    im2: "/photo/image8.png",
    im3: "/photo/watch.jpg",
  },
  {
    productId: "6",
    name: "Neckband",
    description:
      "Fastrack Fpods(New Launch) FX100 Bluetooth TWS In-Ear Earbuds with 40 Hrs Playtime|BT V5.3|13mm Extra Deep Bass Drivers|Quad Mic ENC for Clear Calls|Ultra Low 50ms Latency Gaming Mode|NitroFast Charge",
    price: " 299",
    image: "/photo/image9.png",
    category: "Headphone",
    im1: "/photo/image11.png",
    im2: "/photo/image12.png",
    im3: "/photo/image9.png",
  },
  {
    productId: "7",
    name: "Salwar-Suit",
    description:
      "SGF11 Women's Trendy Kanjivaram Soft Lichi Silk Saree With Blouse Piece SWADESI STUFF Georgette Saree with Banglory Silk Blouse & Stunning Crystal Fix Embellishments - Indian Ethnic Wear for Women",
    price: " 199",
    image: "/photo/women2.jpeg",
    category: "Cloths",
    im1: "/photo/women6.jpg",
    im2: "/photo/women7.jpg",
    im3: "/photo/women-4.jpg",
  },
  {
    productId: "8",
    name: "Rockerz",
    description:
      "Fastrack Fpods(New Launch) FX100 Bluetooth TWS In-Ear Earbuds with 40 Hrs Playtime|BT V5.3|13mm Extra Deep Bass Drivers|Quad Mic ENC for Clear Calls|Ultra Low 50ms Latency Gaming Mode|NitroFast Charge",
    price: " 399",
    image: "/photo/image16.png",
    category: "Headphone",
    im1: "/photo/image13.png",
    im2: "/photo/image14.png",
    im3: "/photo/image16.png",
  },
  {
    productId: "9",
    name: "Salwar Suit",
    description:
      "SGF11 Women's Trendy Kanjivaram Soft Lichi Silk Saree With Blouse Piece SWADESI STUFF Georgette Saree with Banglory Silk Blouse & Stunning Crystal Fix Embellishments - Indian Ethnic Wear for Women",
    price: " 199",
    image: "/photo/women7.jpg",
    category: "Cloths",
    im1: "/photo/women2.jpeg",
    im2: "/photo/women6.jpg",
    im3: "/photo/women-4.jpg",
  },
  {
    productId: "10",
    name: "wave call",
    description:
      "Noise Twist Go Round dial Smartwatch with BT Calling, 1.39 Display, Metal Build, 100+ Watch Faces, IP68, Sleep Tracking, 100+ Sports Modes, 24/7 Heart Rate Monitoring (Jet Black)",
    price: " 399",
    image: "/photo/watch-3.jpg",
    category: "Watches",
    im1: "/photo/image5.png",
    im2: "/photo/watch-1.jpg",
    im3: "/photo/watch.jpg",
  },
  {
    productId: "11",
    name: "Rockid Rush",
    description:
      "Fastrack Fpods(New Launch) FX100 Bluetooth TWS In-Ear Earbuds with 40 Hrs Playtime|BT V5.3|13mm Extra Deep Bass Drivers|Quad Mic ENC for Clear Calls|Ultra Low 50ms Latency Gaming Mode|NitroFast Charge",
    price: " 499",
    image: "/photo/image13.png",
    category: "Headphone",
    im1: "/photo/image14.png",
    im2: "/photo/image16.png",
    im3: "/photo/image13.png",
  },
  {
    productId: "12",
    name: "Office Wear",
    description:
      "GRECIILOOKS Men Solid Regular Fit Casual Shirt Lymio Casual Shirt for Men|| Shirt for Men|| Men Stylish Shirt",
    price: " 299",
    image: "/photo/men2.png",
    category: "Cloths",
    im1: "/photo/men4.png",
    im2: "/photo/men3.jpg",
    im3: "/photo/men-1.jpg",
  },
];
export default Catagories;
